@startuml

start

:user provides sorting method by name or age;
:system retrieves the animals;

if (sorting by name) then (yes)
    :system sorts the animals by name;
    stop;
else (no, sort by age)
    :system sorts the animals by age;
    stop;



@enduml
